version: "3.0"
services:

  mysql:
    container_name: "mysql_techlegal"
    image: mysql:8.4.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dwh
      MYSQL_USER: dwh
      MYSQL_PASSWORD: dwhpassword
    ports:
      - '3306:3306'