"""Add fields to techlegal_credits table

Revision ID: 2f728a5670a2
Revises: 502cbebf4db4
Create Date: 2025-04-30 13:41:01.333367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f728a5670a2'
down_revision: Union[str, None] = '502cbebf4db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('techlegal_credits', sa.Column('dateFamilMaterial', sa.String(length=10), nullable=True))
    op.add_column('techlegal_credits', sa.Column('chatLastMsg', sa.Text, nullable=True))
    op.add_column('techlegal_credits', sa.Column('chatLastMsgTime', sa.String(length=10), nullable=True))
    op.add_column('techlegal_credits', sa.Column('isPrimaryCollector', sa.String(length=64), nullable=True))
    op.add_column('techlegal_credits', sa.Column('amountPriorityAmount', sa.Float(), nullable=True))
    op.add_column('techlegal_credits', sa.Column('creditAuditTransfers', sa.String(length=64), nullable=True))
    op.add_column('techlegal_credits', sa.Column('ep_last_rest_debit', sa.Float(), nullable=True))
    op.add_column('techlegal_credits', sa.Column('numberCase', sa.String(length=256), nullable=True))
    op.add_column('techlegal_credits', sa.Column('isSubsistenceMin', sa.String(length=256), nullable=True))
    op.add_column('techlegal_credits', sa.Column('edCompany_name', sa.String(length=256), nullable=True))
    op.add_column('techlegal_credits', sa.Column('epAppealCompany_name', sa.String(length=256), nullable=True))
    op.add_column('techlegal_credits', sa.Column('credit_agreements_briefcase_name', sa.String(length=256), nullable=True))
    op.add_column('techlegal_credits', sa.Column('debtor_inn_invalid_date', sa.String(length=5), nullable=True))
    op.add_column('techlegal_credits', sa.Column('bailiff_executor_fio', sa.String(length=256), nullable=True))
    op.add_column('techlegal_credits', sa.Column('bailiff_executor_phone', sa.String(length=256), nullable=True))
    op.add_column('techlegal_credits', sa.Column('dtr_inn', sa.String(length=64), nullable=True))
    op.add_column('techlegal_credits', sa.Column('note', sa.Text, nullable=True))
    op.add_column('techlegal_credits', sa.Column('yfssp_name', sa.Text, nullable=True))
    op.add_column('techlegal_credits', sa.Column('edTp_name', sa.String(length=64), nullable=True))
    op.add_column('techlegal_credits', sa.Column('dateRequestDeath', sa.String(length=10), nullable=True))
    op.add_column('techlegal_credits', sa.Column('dateDeath', sa.String(length=10), nullable=True))
    op.add_column('techlegal_credits', sa.Column('inn_invalid_date', sa.String(length=10), nullable=True))
    op.add_column('techlegal_credits', sa.Column('dateLastUpdateStatusCa', sa.String(length=10), nullable=True))
    op.add_column('techlegal_credits', sa.Column('ep_rs_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('techlegal_credits', 'ep_rs_name')
    op.drop_column('techlegal_credits', 'dateLastUpdateStatusCa')
    op.drop_column('techlegal_credits', 'inn_invalid_date')
    op.drop_column('techlegal_credits', 'dateDeath')
    op.drop_column('techlegal_credits', 'dateRequestDeath')
    op.drop_column('techlegal_credits', 'edTp_name')
    op.drop_column('techlegal_credits', 'yfssp_name')
    op.drop_column('techlegal_credits', 'note')
    op.drop_column('techlegal_credits', 'dtr_inn')
    op.drop_column('techlegal_credits', 'bailiff_executor_phone')
    op.drop_column('techlegal_credits', 'bailiff_executor_fio')
    op.drop_column('techlegal_credits', 'debtor_inn_invalid_date')
    op.drop_column('techlegal_credits', 'credit_agreements_briefcase_name')
    op.drop_column('techlegal_credits', 'epAppealCompany_name')
    op.drop_column('techlegal_credits', 'edCompany_name')
    op.drop_column('techlegal_credits', 'isSubsistenceMin')
    op.drop_column('techlegal_credits', 'numberCase')
    op.drop_column('techlegal_credits', 'ep_last_rest_debit')
    op.drop_column('techlegal_credits', 'creditAuditTransfers')
    op.drop_column('techlegal_credits', 'amountPriorityAmount')
    op.drop_column('techlegal_credits', 'isPrimaryCollector')
    op.drop_column('techlegal_credits', 'chatLastMsgTime')
    op.drop_column('techlegal_credits', 'chatLastMsg')
    op.drop_column('techlegal_credits', 'dateFamilMaterial')
    # ### end Alembic commands ###
