"""Add has_error field to log table

Revision ID: 502cbebf4db4
Revises: f8c7725afa58
Create Date: 2025-04-27 11:37:49.883661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '502cbebf4db4'
down_revision: Union[str, None] = 'f8c7725afa58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('techlegal_epexist', 'debtor',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'osp_name',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'spi_short_name',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'ep_subject_execution',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'ed_issuing_authority',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'response_doc_name',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('techlegal_logs', sa.Column('has_error', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('techlegal_logs', 'has_error')
    op.alter_column('techlegal_epexist', 'response_doc_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'ed_issuing_authority',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'ep_subject_execution',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'spi_short_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'osp_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('techlegal_epexist', 'debtor',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
