"""'initial'

Revision ID: c2a4b82146c8
Revises: 
Create Date: 2025-04-06 12:00:07.470161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a4b82146c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techlegal_credits',
    sa.Column('credit_number', sa.String(length=255), nullable=False),
    sa.Column('credit_id', sa.BIGINT(), nullable=True),
    sa.Column('debtor', sa.String(length=255), nullable=False),
    sa.Column('debtor_birthdate', sa.Date(), nullable=True),
    sa.Column('osp_name', sa.String(length=500), nullable=True),
    sa.Column('ep_number', sa.String(length=255), nullable=True),
    sa.Column('ep_date_start', sa.Date(), nullable=True),
    sa.Column('ep_date_end', sa.Date(), nullable=True),
    sa.Column('ep_completion_basis', sa.String(length=255), nullable=True),
    sa.Column('ep_rest_debit', sa.Float(), nullable=True),
    sa.Column('collector', sa.String(length=255), nullable=True),
    sa.Column('is_pension', sa.String(length=50), nullable=True),
    sa.Column('credit_status', sa.String(length=255), nullable=True),
    sa.Column('debtor_is_snils', sa.String(length=50), nullable=True),
    sa.Column('credit_date_start', sa.Date(), nullable=True),
    sa.Column('credit_date_end', sa.Date(), nullable=True),
    sa.Column('ep_status', sa.String(length=255), nullable=True),
    sa.Column('is_ep_confirmation', sa.String(length=50), nullable=True),
    sa.Column('responsible_user_fio', sa.String(length=255), nullable=True),
    sa.Column('date_fssp_request', sa.Date(), nullable=True),
    sa.Column('ed_number', sa.String(length=128), nullable=True),
    sa.Column('ed_date', sa.Date(), nullable=True),
    sa.Column('debtor_gender', sa.String(length=10), nullable=True),
    sa.Column('credit_agreements_suspended', sa.String(length=50), nullable=True),
    sa.Column('dtr_is_pasport', sa.String(length=50), nullable=True),
    sa.Column('receipts_before_input', sa.Integer(), nullable=True),
    sa.Column('receipts_after_entering', sa.Integer(), nullable=True),
    sa.Column('receipts_last_month', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('slice_tag', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techlegal_credits_credit_id'), 'techlegal_credits', ['credit_id'], unique=False)
    op.create_index(op.f('ix_techlegal_credits_slice_tag'), 'techlegal_credits', ['slice_tag'], unique=False)
    op.create_table('techlegal_logs',
    sa.Column('slice_tag', sa.String(length=25), nullable=False),
    sa.Column('tablename', sa.String(length=25), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techlegal_logs_slice_tag'), 'techlegal_logs', ['slice_tag'], unique=False)
    op.create_table('techlegal_requests',
    sa.Column('epNumber', sa.String(length=50), nullable=True),
    sa.Column('requestName', sa.Text(), nullable=False),
    sa.Column('collector', sa.String(length=255), nullable=False),
    sa.Column('debtor', sa.String(length=255), nullable=False),
    sa.Column('requestNumber', sa.String(length=50), nullable=True),
    sa.Column('requestDate', sa.Date(), nullable=True),
    sa.Column('dateDocument', sa.Date(), nullable=True),
    sa.Column('requestStatus', sa.String(length=100), nullable=True),
    sa.Column('isRequestInZip', sa.String(length=10), nullable=False),
    sa.Column('dateRequestInZip', sa.Date(), nullable=True),
    sa.Column('responseDocName', sa.String(length=255), nullable=True),
    sa.Column('responseDocDate', sa.Date(), nullable=True),
    sa.Column('ospName', sa.Text(), nullable=True),
    sa.Column('responseText', sa.Text(), nullable=True),
    sa.Column('textResolution', sa.Text(), nullable=True),
    sa.Column('dateUpdate', sa.Date(), nullable=True),
    sa.Column('caNumber', sa.String(length=255), nullable=False),
    sa.Column('userName', sa.String(length=512), nullable=False),
    sa.Column('requestIsAppeal', sa.String(length=255), nullable=True),
    sa.Column('edNumber', sa.String(length=128), nullable=True),
    sa.Column('edDate', sa.Date(), nullable=True),
    sa.Column('idCreditFirm', sa.BIGINT(), nullable=False),
    sa.Column('ca_dateStart', sa.Date(), nullable=False),
    sa.Column('ca_dateEnd', sa.Date(), nullable=True),
    sa.Column('rqSource', sa.String(length=100), nullable=False),
    sa.Column('credit_agreements_briefcase', sa.String(length=255), nullable=True),
    sa.Column('resSingName', sa.String(length=255), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('slice_tag', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techlegal_requests_idCreditFirm'), 'techlegal_requests', ['idCreditFirm'], unique=False)
    op.create_index(op.f('ix_techlegal_requests_slice_tag'), 'techlegal_requests', ['slice_tag'], unique=False)
    op.create_table('techlegal_subjects',
    sa.Column('debtor', sa.String(length=255), nullable=False),
    sa.Column('subjectType', sa.String(length=255), nullable=True),
    sa.Column('subjectInfo', sa.Text(), nullable=True),
    sa.Column('epAmountOwed', sa.Float(), nullable=True),
    sa.Column('epRestDebit', sa.Float(), nullable=True),
    sa.Column('epNumber', sa.String(length=128), nullable=True),
    sa.Column('epDateStart', sa.Date(), nullable=True),
    sa.Column('ospName', sa.Text(), nullable=True),
    sa.Column('collector', sa.String(length=512), nullable=False),
    sa.Column('worthInCashAccount', sa.Float(), nullable=True),
    sa.Column('subjectMeasureName', sa.Text(), nullable=True),
    sa.Column('subjectMeasureDate', sa.Date(), nullable=True),
    sa.Column('dateRelevant', sa.Date(), nullable=True),
    sa.Column('caNumber', sa.String(length=256), nullable=False),
    sa.Column('ca_dateStart', sa.Date(), nullable=True),
    sa.Column('ca_dateEnd', sa.Date(), nullable=True),
    sa.Column('responsibleUser_fio', sa.String(length=512), nullable=False),
    sa.Column('idCreditFirm', sa.BIGINT(), nullable=True),
    sa.Column('edNumber', sa.String(length=128), nullable=True),
    sa.Column('edDate', sa.Date(), nullable=True),
    sa.Column('caStatus', sa.String(length=100), nullable=False),
    sa.Column('requestDate', sa.Date(), nullable=True),
    sa.Column('numberGD', sa.String(length=100), nullable=True),
    sa.Column('dateGD', sa.Date(), nullable=True),
    sa.Column('credit_agreements_briefcase', sa.String(length=255), nullable=True),
    sa.Column('creditId', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('slice_tag', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techlegal_subjects_idCreditFirm'), 'techlegal_subjects', ['idCreditFirm'], unique=False)
    op.create_index(op.f('ix_techlegal_subjects_slice_tag'), 'techlegal_subjects', ['slice_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_techlegal_subjects_slice_tag'), table_name='techlegal_subjects')
    op.drop_index(op.f('ix_techlegal_subjects_idCreditFirm'), table_name='techlegal_subjects')
    op.drop_table('techlegal_subjects')
    op.drop_index(op.f('ix_techlegal_requests_slice_tag'), table_name='techlegal_requests')
    op.drop_index(op.f('ix_techlegal_requests_idCreditFirm'), table_name='techlegal_requests')
    op.drop_table('techlegal_requests')
    op.drop_index(op.f('ix_techlegal_logs_slice_tag'), table_name='techlegal_logs')
    op.drop_table('techlegal_logs')
    op.drop_index(op.f('ix_techlegal_credits_slice_tag'), table_name='techlegal_credits')
    op.drop_index(op.f('ix_techlegal_credits_credit_id'), table_name='techlegal_credits')
    op.drop_table('techlegal_credits')
    # ### end Alembic commands ###
