"""Add techlegal_epexist table

Revision ID: f8c7725afa58
Revises: c2a4b82146c8
Create Date: 2025-04-06 13:28:55.677181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c7725afa58'
down_revision: Union[str, None] = 'c2a4b82146c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techlegal_epexist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debtor', sa.String(length=256), nullable=True),
    sa.Column('debtor_birthdate', sa.String(length=10), nullable=True),
    sa.Column('debtor_inn', sa.String(length=64), nullable=True),
    sa.Column('osp_name', sa.String(length=256), nullable=True),
    sa.Column('spi_short_name', sa.String(length=256), nullable=True),
    sa.Column('ep_number', sa.String(length=128), nullable=True),
    sa.Column('ep_date_start', sa.String(length=10), nullable=True),
    sa.Column('ep_status', sa.String(length=10), nullable=True),
    sa.Column('ep_date_end', sa.String(length=10), nullable=True),
    sa.Column('ep_completion_basis', sa.String(length=64), nullable=True),
    sa.Column('ep_rest_debit', sa.Float(), nullable=True),
    sa.Column('ep_subject_execution', sa.String(length=256), nullable=True),
    sa.Column('number_cd', sa.String(length=128), nullable=True),
    sa.Column('ed_number', sa.String(length=128), nullable=True),
    sa.Column('ed_date', sa.String(length=10), nullable=True),
    sa.Column('ed_issuing_authority', sa.String(length=256), nullable=True),
    sa.Column('ed_company_name', sa.String(length=256), nullable=True),
    sa.Column('ed_company_inn', sa.String(length=64), nullable=True),
    sa.Column('collector', sa.String(length=512), nullable=True),
    sa.Column('collector_inn', sa.String(length=64), nullable=True),
    sa.Column('date_fssp_request', sa.String(length=10), nullable=True),
    sa.Column('request_date', sa.String(length=10), nullable=True),
    sa.Column('date_document', sa.String(length=10), nullable=True),
    sa.Column('request_status', sa.String(length=128), nullable=True),
    sa.Column('is_request_in_zip', sa.String(length=5), nullable=True),
    sa.Column('date_request_in_zip', sa.String(length=10), nullable=True),
    sa.Column('response_doc_name', sa.String(length=256), nullable=True),
    sa.Column('response_doc_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('slice_tag', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techlegal_epexist_slice_tag'), 'techlegal_epexist', ['slice_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_techlegal_epexist_slice_tag'), table_name='techlegal_epexist')
    op.drop_table('techlegal_epexist')
    # ### end Alembic commands ###
